### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by Islati** [bit-js/byte#1]
Any suggestions?

**Comment by aquapi** [comment]
@Islati I won't be rolling my own WebSocket implementation since there is gonna be a lot of overhead.
I believe there are packages like `ws` in Node or Deno to handle this.
If you are using Bun, I think my WebSocket router will work for you: https://www.npmjs.com/package/@bit-js/bun-utils
Also if you have other questions, please join the `bit-js` project discord server here: https://discord.gg/KAGDBX9a
